services:
  web:
    build: .
    command: "uvicorn app.main:app --host 0.0.0.0 --port 9013 --proxy-headers --forwarded-allow-ips='*'"
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - 9013:9013

  redis:
    image: redis
    restart: unless-stopped
